import {
  sentenceConllToJson,
  sentenceJsonToConll,
  emptySentenceJson,
  emptyMetaJson,
  emptyTreeJson,
  emptyTokenJson,
  emptyFeaturesJson,
  emptyDepsJson,
  emptyNodesOrGroupsJson,
  replaceArrayOfTokens,
  constructTextFromTreeJson,
  returnTokensInOrder,
  getNodeFromTreeJson,
} from './conll';

export default {
  sentenceConllToJson,
  sentenceJsonToConll,
  emptySentenceJson,
  emptyMetaJson,
  emptyTreeJson,
  emptyTokenJson,
  emptyFeaturesJson,
  emptyNodesOrGroupsJson,
  emptyDepsJson,
  replaceArrayOfTokens,
  constructTextFromTreeJson,
  returnTokensInOrder,
  getNodeFromTreeJson,
};
